### PR TITLE
Created a short URL

### PR DESCRIPTION
**Pull request by JJ**
I did it for my Python book, but I guess I could as well include it here, just in case. Easier to remember, too. It's using Github's own shortener, check it out, it's quite nifty.

### CODE REVIEW

**Comment by obestwalter** [comment]
Hi @JJ thanks - which book is that?

**Comment by JJ** [comment]
This one
https://www.amazon.es/dp/B073T47421/ref=sr_1_4?s=books&ie=UTF8&qid=1499598466&sr=1-4&keywords=jj+merelo
It's in Spanish :-)

**Comment by obestwalter** [comment]
o.k. - sadly I don't speak spanish :(

BTW: We already have a another short url provided by another user: https://github.com/pyenv/pyenv-installer/issues/41

**Comment by obestwalter** [comment]
Closing this as stale and not really necessary.

**Pull request closed without merging**
