### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by jaycenhorton**

### CODE REVIEW

**Comment by obestwalter** [comment]
Hi @jaycenhorton, thanks for the PR. Can you elaborate, why this would be preferable?

**Comment by obestwalter** [comment]
I guess it's related to https://github.com/pyenv/pyenv-installer/issues/63?

**Comment by jaycenhorton** [comment]
That is correct. Adding to profile does not work, bashrc works fine. It is also consistent with the readme to use bashrc instead. :)

**Comment by obestwalter** [comment]
LGTM then :)

**Pull request merged**
